In [16]:
#Here we will be trying to predict the recipee for 
#muffins, scones and cupcakes by using the amount of
#sugar butter and flour required by each item
#by KMEANS Algorithm

In [17]:
#immporting the required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import seaborn as sns

In [18]:
#importing the datasset
X = pd.read_csv("recipes_muffins_cupcakes_scones.csv")
#X

Type  Flour  Milk  Sugar  Butter  Egg  Baking Powder  Vanilla  Salt
0    Muffin     55    28      3       7    5              2        0     0
1    Muffin     47    24     12       6    9              1        0     0
2    Muffin     47    23     18       6    4              1        0     0
3    Muffin     45    11     17      17    8              1        0     0
4    Muffin     50    25     12       6    5              2        1     0
5    Muffin     55    27      3       7    5              2        1     0
6    Muffin     54    27      7       5    5              2        0     0
7    Muffin     47    26     10      10    4              1        0     0
8    Muffin     50    17     17       8    6              1        0     0
9    Muffin     50    17     17      11    4              1        0     0
10  Cupcake     39     0     26      19   14              1        1     0
11  Cupcake     42    21     16      10    8              3        0     0
12  Cupcake     34    17     20      20    5              2        1     0
13  Cupcake     39    13     17      19   10              1        1     0
14  Cupcake     38    15     23      15    8              0        1     0
15  Cupcake     42    18     25       9    5              1        0     0
16  Cupcake     36    14     21      14   11              2        1     0
17  Cupcake     38    15     31       8    6              1        1     0
18  Cupcake     36    16     24      12    9              1        1     0
19  Cupcake     34    17     23      11   13              0        1     0
20    Scone     29     3     46       6    0             11        0     6
21    Scone     19     3     36       3   14              7       14     5
22    Scone     20     5     52       5   10              3        0     5
23    Scone     19     6     50       5    6             10        0     3
24    Scone     19    10     51       5    0             10        0     5

In [21]:
#slicing out the required dataset from the whole data
X1 = X[["Flour","Sugar","Butter"]]
X1

Flour  Sugar  Butter
0      55      3       7
1      47     12       6
2      47     18       6
3      45     17      17
4      50     12       6
5      55      3       7
6      54      7       5
7      47     10      10
8      50     17       8
9      50     17      11
10     39     26      19
11     42     16      10
12     34     20      20
13     39     17      19
14     38     23      15
15     42     25       9
16     36     21      14
17     38     31       8
18     36     24      12
19     34     23      11
20     29     46       6
21     19     36       3
22     20     52       5
23     19     50       5
24     19     51       5

In [23]:
#fitting and training the data

#labels give the cluster numbering for the training set itself
#thus can be validated whether clustering was good or not

kmeans = KMeans(n_clusters=3, random_state=0).fit(X1)

kmeans.labels_

array([1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2,
       2, 2, 2])

In [24]:
#predicting the new points
#So now, if we put arbitrary values we can test 
#in which cluster does the values go to
#if we see its fine, we can deploy the algo for the required problem statement
kmeans.predict([[36, 24,7], [56, 6,19],[19,52,3]])

array([0, 1, 2])

In [25]:
#cluster centres being tried

kmeans.cluster_centers_

array([[38.45454545, 22.09090909, 14.        ],
       [50.55555556, 11.        ,  7.33333333],
       [21.2       , 47.        ,  4.8       ]])

In [26]:
flour = input('Enter the flour...')
sugar = input('Enter the sugar...')
butter = input('Enter the butter...')
x = kmeans.predict([[flour,sugar,butter]])
if x == 1:
    print("it is a muffin recipee")
elif x == 0:
    print("it is a cupcake recipee")
else:
    print("it is a scones recipee") 

Enter the flour...36
Enter the sugar...19
Enter the butter...18
it is a cupcake recipee
